### ISSUE TITLE
Create file architecture

### ISSUE THREAD

**Issue by vince-pan** [vince-pan/getBulkData#1]
Create folders and empty files for software architecture.

**Comment by vince-pan** [comment]
@matthias-hbt, j'ai créé l'architecture des fichiers, dis-moi si tu as des commentaires.

**Comment by matthias-hbt** [comment]
Cool, ça m'a permis de tester de clone et ça marche nickel ! 
Par rapport à l'architecture des fichiers, c'est du détails mais on avait pas dit qu'on faisait un dossier entities ? je vois que t'as mis bulk.py dans le dossier getBulkData donc les autres (ex : part.py, fastener.py, etc.) tu les mets ici aussi ? Pour ce qui est du main.py tu le verrai au niveau du README et requirements.txt ?

**Comment by vince-pan** [comment]
Yes, j’ai changé pas mal de choses : On pourrait mettre toutes les classes dans bulk.py et le main aussi pour simplifier un peu.
Mais c’est pas figé, si c’est trop contraignant, on modifiera !
